<html>
<head>
    <meta charset="UTF-8"/>
</head>
<body>
<aside class="col-md-4 blog-sidebar">
    <div class="p-3">
        <h4 class="font-italic"><@spring.message 'footer.read'/></h4>
        <ol class="list-unstyled">
            <li><a href="${rc.getContextPath()}/change?locale=ru_RU">Русский</a></li>
            <li><a href="${rc.getContextPath()}/change?locale=en_EN">English</a></li>
            <li><a href="#">Deutsche</a></li>
        </ol>
    </div>
</aside>
</body>
</html>
